/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'ATK_ESP8266' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"

/* MDK-Packs::Data Exchange:JSON:cJSON@1.7.7 */
#define RTE_DataExchange_JSON_cJSON     /* cJSON */
/* MDK-Packs::IoT Utility:MQTTPacket@1.1.0 */
#define RTE_IoT_MQTTPacket              /* IoT MQTTPacket */


#endif /* RTE_COMPONENTS_H */
